language: node_js
node_js:
  - "node"
install:
  - npm install
  - cd functions/ && npm install && cd ..
before_script:
  - npm run lint
  - if [ "$TRAVIS_TAG" ]; then sed -i 's/corpopong-dev/corpopong/g' ./src/corpopong-app/corpopong-app.html; fi
  - if [ "$TRAVIS_TAG" ]; then sed -i 's/corpopong-dev/corpopong/g' ./src/common/api-ajax.html; fi
  - if [ "$TRAVIS_TAG" ]; then sed -i 's/AIzaSyB1jdeJaOejjpVtL5SOQrkiARsmAdeyuOk/AIzaSyDbtyN2aekFdVcqWP-YbclBHkwknQOrk6U/' ./src/corpopong-app/corpopong-app.html; fi
  - if [ "$TRAVIS_TAG" ]; then sed -i 's/414017409980/182128657968/' ./src/corpopong-app/corpopong-app.html; fi
  - npm run autoprefixer
script:
  - npm run build
deploy:
  - provider: firebase
    project: "corpopong-dev"
    skip_cleanup: true
    on:
      condition: "-z $TRAVIS_TAG"
      all_branches: true
  - provider: firebase
    project: "corpopong"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
